version: '3'

################################################################################
# NETWORK
################################################################################
networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.26.100.0/24
services:
  os:
    image: vitamin/alpine:3.6
    labels:
      com.vitamin.description: "base os for a vitamin"
      com.vitamin.department: "vitamin department"
      com.vitamin.release: "v1.0"
    build: 
      context: ${HOST_DEV_BOX_PATH}/docker/os/alpine
  bind:
    image: vitamin/bind:0.11
    build:
      context: "${HOST_DEV_BOX_PATH}/docker/services/bind"
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${LOCAL_LISTEN_ADDR}${HOST_PORT_BIND:-1053}:53"
      - "${LOCAL_LISTEN_ADDR}${HOST_PORT_BIND:-1053}:53/udp"     
    environment:
      - WILDCARD_DOMAIN=${TLD_SUFFIX:-loc}
      - WILDCARD_ADDRESS=172.26.100.10
      - DNS_FORWARDER=${BIND_DNS_RESOLVER:-114.114.114.114}
    dns:
      - 127.0.0.1
    networks:
      app_net:
        ipv4_address: 172.26.100.9
    depends_on:
      - os
  nginx:
    image: vitamin/nginx:1.13
    build:
      context: ${HOST_DEV_BOX_PATH}/docker/services/nginx
      args:
        version: 1.13
    volumes:
      - ${HOST_PATH_NGINX_CONFIG_DIR}/nginx.conf:/etc/nginx/nginx.conf:rw
      - ${HOST_PATH_NGINX_CONFIG_DIR}/conf.d/:/etc/nginx/conf.d/:rw
      - ${HOST_PATH_DEPLOY_DATADIR}:/apps:rw
      - ${HOST_PATH_RUN_DIR}/nginx:/var/run/nginx:rw
    environment:
      - NEW_UID
      - NEW_GID
    
    networks:
      app_net:
        ipv4_address: 172.26.100.11
    depends_on:
      - os
      - bind
  php7:
    image: vitamin/php:7.1
    build: 
      context: ${HOST_DEV_BOX_PATH}/docker/services/php
      dockerfile: Dockerfile
      args:
        dev_user: roy
    volumes:
      - ${HOST_PATH_PHP_CONFIG_DIR}/php.ini:/etc/php/php.ini:ro
      - ${HOST_PATH_PHP_CONFIG_DIR}/php-fpm.d:/etc/php/php-fpm.d:ro
      - ${HOST_PATH_PHP_CONFIG_DIR}/php-fpm.conf:/etc/php/php-fpm.conf:ro
      - ${HOST_LOG_PHP_DIR}:/var/log/php:rw
      - ${HOST_PATH_DEPLOY_DATADIR}:/apps:rw
      - ${HOST_PATH_RUN_DIR}/php:/var/run/php:rw
    environment:
      - NEW_UID
      - NEW_GID
    networks:
      app_net:
        ipv4_address: 172.26.100.10
    depends_on:
      - os
      - nginx
      - mysql
  mysql:
    image: vitamin/mariadb:10.1
    build: 
      context: ${HOST_DEV_BOX_PATH}/docker/services/mysql
      dockerfile: Dockerfile
      args:
        dev_user: roy
    volumes:
      - ${HOST_PATH_MYSQL_DATADIR}:/var/lib/mysql:rw
      - ${HOST_LOG_MYSQL_DIR}}:/var/log/mysql:rw
      - ${HOST_CONFIG_MYSQL_DIR}/my.cnf:/etc/my.cnf:rw
      - ${HOST_PATH_RUN_DIR}/mysql:/var/run/mysql:rw
    depends_on:
      - os
      - bind
    networks:
      app_net:
        ipv4_address: 172.26.100.12